version: 2.1

executors:
  node-executor:
    docker:
      - image: cimg/node:18.17

jobs:
  build:
    executor: node-executor
    steps:
      - checkout
      - setup_remote_docker:
          version: 20.10.7
      - restore_cache:
          keys:
            - node-cache-{{ checksum "package-lock.json" }}
            - node-cache-
      - run:
          name: Install dependencies
          command: npm install
      - save_cache:
          paths:
            - ~/.npm
          key: node-cache-{{ checksum "package-lock.json" }}
      - run:
          name: Build application
          command: npm run build
      - persist_to_workspace:
          root: .
          paths:
            - build
            - firebase.json
            - database.rules.json
            - firestore.rules
            - firestore.indexes.json
            - storage.rules

  deploy:
    executor: node-executor
    steps:
      - attach_workspace:
          at: /home/circleci/project
      - run:
          name: Deploy to Firebase
          command: npx firebase-tools deploy --token $FIREBASE_TOKEN --project meta-scraper-1bad5

workflows:
  version: 2
  build_and_deploy:
    jobs:
      - build
      - deploy:
          requires:
            - build
          filters:
            branches:
              only:
                - master
